# General Jekyll Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/
url: https://herrkaefer.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: "true"
